version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      TZ: Asia/Seoul
    restart: always
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true